import "dotenv/config";
import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

const SAMPLE_INSTITUTIONS = [
  {
    name: "Chase",
    type: "bank",
    primaryBureau: "experian",
    bureausPulled: JSON.stringify(["experian", "equifax"]),
    products: JSON.stringify(["Ink Business Preferred", "Ink Business Unlimited", "Ink Business Cash"]),
    approvalFactors: JSON.stringify(["relationship", "inquiries sensitivity", "revenue", "utilization"]),
    notes: "Often pulls Experian for business. Relationship and 5/24 matter.",
    sourceLinks: JSON.stringify(["https://www.doctorofcredit.com/"]),
    tags: JSON.stringify(["business cards", "0% APR", "relationship bank"]),
    state: null,
  },
  {
    name: "American Express",
    type: "bank",
    primaryBureau: "experian",
    bureausPulled: JSON.stringify(["experian"]),
    products: JSON.stringify(["Business Platinum", "Business Gold", "Blue Business Plus"]),
    approvalFactors: JSON.stringify(["relationship", "income", "existing Amex"]),
    notes: "Primarily Experian. Often instant approval for existing customers.",
    sourceLinks: JSON.stringify(["https://www.doctorofcredit.com/"]),
    tags: JSON.stringify(["business cards", "charge cards", "relationship bank"]),
    state: null,
  },
  {
    name: "Bank of America",
    type: "bank",
    primaryBureau: "transunion",
    bureausPulled: JSON.stringify(["transunion", "equifax"]),
    products: JSON.stringify(["Business Advantage", "Business Preferred Rewards"]),
    approvalFactors: JSON.stringify(["relationship", "deposits", "inquiries"]),
    notes: "BofA often pulls TransUnion. Preferred Rewards helps with limits.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards", "relationship bank"]),
    state: null,
  },
  {
    name: "Wells Fargo",
    type: "bank",
    primaryBureau: "experian",
    bureausPulled: JSON.stringify(["experian", "equifax"]),
    products: JSON.stringify(["Business Platinum", "Business Elite"]),
    approvalFactors: JSON.stringify(["relationship", "credit history", "utilization"]),
    notes: "Mixed data points; Experian common. Relationship helps.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Capital One",
    type: "bank",
    primaryBureau: "transunion",
    bureausPulled: JSON.stringify(["transunion", "equifax", "experian"]),
    products: JSON.stringify(["Spark Cash", "Spark Miles", "Venture"]),
    approvalFactors: JSON.stringify(["inquiries sensitivity", "utilization", "revenue"]),
    notes: "Can pull all three. Inquiry-sensitive. Revenue verification possible.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards", "high limits"]),
    state: null,
  },
  {
    name: "US Bank",
    type: "bank",
    primaryBureau: "transunion",
    bureausPulled: JSON.stringify(["transunion", "equifax"]),
    products: JSON.stringify(["Business Altitude", "Business Triple Cash"]),
    approvalFactors: JSON.stringify(["relationship", "inquiries", "state"]),
    notes: "TU/Equifax common. Not in all states.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Citi",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "experian"]),
    products: JSON.stringify(["Premier", "Double Cash", "Business"]),
    approvalFactors: JSON.stringify(["relationship", "inquiries", "income"]),
    notes: "Equifax often primary. 8/65 rule for applications.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Navy Federal Credit Union",
    type: "credit_union",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "experian"]),
    products: JSON.stringify(["Business", "LOC", "Platinum"]),
    approvalFactors: JSON.stringify(["membership", "relationship", "utilization"]),
    notes: "Membership required. Strong relationship benefits.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["credit union", "LOC", "relationship bank"]),
    state: null,
  },
  {
    name: "PenFed Credit Union",
    type: "credit_union",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "transunion"]),
    products: JSON.stringify(["Business", "Power Cash"]),
    approvalFactors: JSON.stringify(["membership", "credit score", "income"]),
    notes: "Open membership. Often Equifax.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["credit union"]),
    state: null,
  },
  {
    name: "Discover",
    type: "bank",
    primaryBureau: "transunion",
    bureausPulled: JSON.stringify(["transunion"]),
    products: JSON.stringify(["Business Card"]),
    approvalFactors: JSON.stringify(["credit history", "utilization", "income"]),
    notes: "TU commonly. Limited business product set.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Brex",
    type: "fintech",
    primaryBureau: "unknown",
    bureausPulled: JSON.stringify([]),
    products: JSON.stringify(["Corporate Card", "No PG"]),
    approvalFactors: JSON.stringify(["revenue", "cash balance", "no personal guarantee"]),
    notes: "No PG; uses company metrics. Not bureau-centric.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["fintech", "no PG", "high limits"]),
    state: null,
  },
  {
    name: "Ramp",
    type: "fintech",
    primaryBureau: "unknown",
    bureausPulled: JSON.stringify([]),
    products: JSON.stringify(["Corporate Card"]),
    approvalFactors: JSON.stringify(["revenue", "bank connection", "no PG"]),
    notes: "Revenue-based. Ties to bank account.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["fintech", "no PG"]),
    state: null,
  },
  {
    name: "TD Bank",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "transunion"]),
    products: JSON.stringify(["Business Cash", "Business Travel"]),
    approvalFactors: JSON.stringify(["relationship", "state", "inquiries"]),
    notes: "East coast focus. Equifax common.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "PNC Bank",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "transunion"]),
    products: JSON.stringify(["Business Credit Card", "Cash Rewards"]),
    approvalFactors: JSON.stringify(["relationship", "deposits", "credit history"]),
    notes: "Regional. Relationship and deposit history help.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Truist",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "transunion"]),
    products: JSON.stringify(["Business Cash", "Business Rewards"]),
    approvalFactors: JSON.stringify(["relationship", "SunTrust/BB&T history"]),
    notes: "Merger of SunTrust and BB&T. Equifax often.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "First National Bank (FNB)",
    type: "bank",
    primaryBureau: "transunion",
    bureausPulled: JSON.stringify(["transunion"]),
    products: JSON.stringify(["Business Card"]),
    approvalFactors: JSON.stringify(["relationship", "state"]),
    notes: "Regional. TU pull common.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "KeyBank",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax"]),
    products: JSON.stringify(["Business Rewards"]),
    approvalFactors: JSON.stringify(["relationship", "income", "state"]),
    notes: "Northeast/Midwest. Equifax primary.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Huntington Bank",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax", "transunion"]),
    products: JSON.stringify(["Business Card"]),
    approvalFactors: JSON.stringify(["relationship", "state"]),
    notes: "Midwest. Mixed bureau reports.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "M&T Bank",
    type: "bank",
    primaryBureau: "equifax",
    bureausPulled: JSON.stringify(["equifax"]),
    products: JSON.stringify(["Business Card"]),
    approvalFactors: JSON.stringify(["relationship", "region"]),
    notes: "Northeast/Mid-Atlantic. Equifax.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards"]),
    state: null,
  },
  {
    name: "Ally Bank",
    type: "bank",
    primaryBureau: "transunion",
    bureausPulled: JSON.stringify(["transunion"]),
    products: JSON.stringify(["Business Card"]),
    approvalFactors: JSON.stringify(["credit score", "utilization"]),
    notes: "Online bank. TU pull reported.",
    sourceLinks: JSON.stringify([]),
    tags: JSON.stringify(["business cards", "fintech"]),
    state: null,
  },
];

async function main() {
  const instCount = await prisma.institution.count();
  if (instCount === 0) {
    for (const row of SAMPLE_INSTITUTIONS) {
      await prisma.institution.create({ data: row });
    }
    console.log(`Seeded ${SAMPLE_INSTITUTIONS.length} institutions.`);
  } else {
    console.log("Institutions already present, skipping institution seed.");
  }
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
